/**
 * Oracle Learning Write-back
 *
 * When a task completes, write a learning summary to ψ/memory/learnings/
 * in the project's Oracle vault. Read-write only to learnings/ directory.
 *
 * This is a lightweight integration — no external API needed.
 * Falls back silently if ψ/ doesn't exist (non-Oracle projects).
 */

import fs from "node:fs";
import path from "node:path";

interface CompletedTask {
  id: string;
  title: string;
  description: string | null;
  project_path: string | null;
  department_id: string | null;
  assigned_agent_id: string | null;
}

interface TaskLog {
  message: string;
  kind: string;
  created_at: number;
}

/**
 * Write a learning file to ψ/memory/learnings/ when a task completes.
 * Silent no-op if project has no ψ/ directory.
 */
export function writeOracleLearning(
  task: CompletedTask,
  logs: TaskLog[],
  agentName?: string,
): void {
  if (!task.project_path) return;

  // Find ψ/memory/learnings/ in project
  const psiPaths = [
    path.join(task.project_path, "ψ", "memory", "learnings"),
    path.join(task.project_path, "psi", "memory", "learnings"),
  ];

  let learningsDir: string | null = null;
  for (const p of psiPaths) {
    try {
      // Resolve symlinks to check real path exists
      const resolved = fs.realpathSync(path.dirname(path.dirname(p)));
      if (fs.existsSync(p) || fs.existsSync(resolved)) {
        fs.mkdirSync(p, { recursive: true });
        learningsDir = p;
        break;
      }
    } catch {
      // Try creating if parent ψ/ exists
      try {
        const psiRoot = path.dirname(path.dirname(p));
        if (fs.existsSync(psiRoot)) {
          fs.mkdirSync(p, { recursive: true });
          learningsDir = p;
          break;
        }
      } catch { /* ψ/ doesn't exist — skip */ }
    }
  }

  if (!learningsDir) return; // No Oracle vault — silent skip

  try {
    const now = new Date();
    const dateStr = now.toISOString().split("T")[0]; // YYYY-MM-DD
    const slug = task.title
      .toLowerCase()
      .replace(/[^a-z0-9ก-๛\s-]/g, "")
      .replace(/\s+/g, "-")
      .slice(0, 50);

    const filename = `${dateStr}_claw-${slug}.md`;
    const filepath = path.join(learningsDir, filename);

    // Don't overwrite existing learnings
    if (fs.existsSync(filepath)) return;

    // Build learning content
    const agent = agentName || "unknown";
    const dept = task.department_id || "unknown";

    // Extract key decisions from task logs
    const keyLogs = logs
      .filter(l => l.kind === "system" || l.kind === "agent")
      .map(l => l.message)
      .filter(m => m.length > 20 && m.length < 500)
      .slice(-5);

    const content = [
      `# Task Complete: ${task.title}`,
      "",
      `**Date**: ${dateStr}`,
      `**Source**: Claw-Empire task (agent: ${agent}, dept: ${dept})`,
      `**Task ID**: ${task.id}`,
      "",
      "## Description",
      task.description || "(no description)",
      "",
      "## Key Decisions",
      ...keyLogs.map(l => `- ${l}`),
      "",
      "## Auto-generated",
      "This learning was auto-generated by Claw-Empire Oracle write-back.",
      "Review and edit to keep only valuable patterns.",
      "",
    ].join("\n");

    fs.writeFileSync(filepath, content, "utf8");
    console.log(`[Oracle] Learning written: ${filepath}`);
  } catch (err) {
    // Silent fail — don't break task completion
    console.warn(`[Oracle] Failed to write learning: ${err}`);
  }
}
